INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR} .)

add_subdirectory(Containers)
add_subdirectory(Utils)
add_subdirectory(CRUDP_Protocol)
add_subdirectory(Servers)
add_subdirectory(GameData)
add_subdirectory(AuthProtocol)
add_subdirectory(Runtime)
if(STANDALONE_ENV)
add_subdirectory(Messages)
endif()
